# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Profile.create(user_id: 1, first_name: 'roger', last_name: "mendez", email: 'roger2923@gmail.com', bio: "25 year old male who loves the outdoors")

# Trail.create(trail_name: "Abrams Falls", features: "Waterfalls", roundtrip: 5.2,  elevation_gain: 675, difficulty:  6 )

# Trail.create(trail_name: "Albright Grove", features: "Forest", roundtrip: 6.7,  elevation_gain: 1475, difficulty:  9 )

# Trail.create(trail_name: "Alum Cave", features: "Views", roundtrip: 4.4,  elevation_gain: 1125, difficulty:  6, popular: true )

# SavedTrail.create(user_id: 1, trail_id: 1, )
# SavedTrail.create(user_id: 1, trail_id: 2, )
# SavedTrail.create(user_id: 1, trail_id: 3, )

Review.create(user_id: 1, trail_id: 1, name: "Roger", comment: "Water fall was really nice to take pictures with. this trail is popular though so expect a crowd during busy times of the year.", difficulty_rating: 4)

# Trail.create(trail_name: "Andrews Bald", features: "Panoramic Views", roundtrip: 3.5,   elevation_gain: 899, difficulty:  5, image_url: "https://res.cloudinary.com/dhzstgmsp/image/upload/v1646153593/Smoky%20Mountains%20Trails/andrews-bald_klel4r.jpg", description:"The trail begins from the Clingmans Dome parking lot and drops elevation to get to Andrews Bald. After a large descent, it levels on a broad ridge, soon diverting to the right at mile 1.1. A final ascension through a forest will bring you to the grassy Andrews Bald, named for the cattle herder, Andres Thompson, who brought livestock up here in the 1840s." )

# Trail.create(trail_name: "Baskins Creek Falls", features: "Waterfalls", roundtrip: 3,  elevation_gain: 953, difficulty:  5, description:"The hike to Baskins Creek Falls, also known as Baskins Falls, begins with a short easy climb. At roughly one-quarter of a mile the terrain levels out where you'll have some decent views of the mountains towards the west, as well as a few glimpses of Gatlinburg - if you're hiking in the winter or early spring. These views, however, will more than likely be obstructed by summer foliage.", image_url: "https://res.cloudinary.com/dhzstgmsp/image/upload/v1646153593/Smoky%20Mountains%20Trails/Baskins_Creek_Falls_omlf8h.jpg" )
# Trail.create(trail_name: "Avent Cabin", features: "Quiet Forest Hike", roundtrip: 2,  elevation_gain: 505, difficulty:  3, description:"From the fairly large parking area, walk through the gate on the far end of the road to begin your hike along the Jakes Creek Trail. Almost immediately you'll begin passing the remnants of several old cottages. Most of these cottages were built in the 1920s, and were used as summer homes by the affluent from the Knoxville area. As of this writing most of the homes along this trail have been razed by the National Park Service. The only artifacts that remain are the chimneys, stone walls, and a few other rock structures that were once part of these homes. The former home of Colonel David C. Chapman also survives, and appears to be one of the few structures that will be preserved and fully restored by the park (see photo on right). Colonel Chapman played an instrumental role in the establishment of Great Smoky Mountains National Park. According to National Park Service documents, the Great Smoky Mountains plans to fully restore 19 structures in the Elkmont District so that they can be opened and viewed by the public. As part of the first phase of the Elkmont restoration project, the National Park Service reopened the old Appalachian Clubhouse for public rental in June of 2011.", image_url: "https://res.cloudinary.com/dhzstgmsp/image/upload/v1646153593/Smoky%20Mountains%20Trails/avent_cabin_ljmtlc.jpg" )
# Trail.create(trail_name: "Balsam High Top", features: "Quiet Forest Hike", roundtrip: 7.6,  elevation_gain: 2535, difficulty:  9, description:"This hike to Balsam High Top begins from the Beech Gap Trailhead. During the summer months when the seasonal Balsam Mountain Road is open, hikers have the option of starting their hike from Pin Oak Gap and taking the Balsam Mountain Trail all the way to the summit. This would shorten your one-way distance by two-tenths of a mile, but more importantly, it would shave off 1275 feet of climbing. Hiking the Beech Gap Trail only makes sense if you don't want to travel along the one-way Balsam Mountain Road, or if you want the additional exercise / challenge, or if your visiting in April, May, or late October when Balsam Mountain Road is closed, and the Straight Fork Road is still open.", image_url: "https://res.cloudinary.com/dhzstgmsp/image/upload/v1646153593/Smoky%20Mountains%20Trails/Balsam_High_Top_i9z3t4.jpg" )
# Trail.create(trail_name: "Bullhead Trail", features: "Views", roundtrip: 5.9,  elevation_gain: 1607, difficulty:  8, description:"On October 25, 2018 Great Smoky Mountains National Park announced the reopening of the Bullhead Trail after being closed for almost two years due to the November 2016 wildfire. On November 23, 2016 two juveniles started a wildfire near the summit of Chimney Tops. By November 28th the fire grew to 500 acres. After several months of exceptional drought conditions, and winds gusts reaching more than 80 mph that afternoon, the fire literally exploded. Over the next several hours it burned almost 18,000 acres, including 11,410 acres within Great Smoky Mountains National Park. From Chimney Tops the fire raced north, passing around the edges of downtown Gatlinburg and reaching the outskirts of Pigeon Forge. Before it was brought under control the fire killed 14 people, injured more than 176 people, and damaged or destroyed at least 2460 structures at a cost of more than $500 million.", image_url: "https://res.cloudinary.com/dhzstgmsp/image/upload/v1646153594/Smoky%20Mountains%20Trails/Bullhead_Trail_cgpiqy.jpg" )
# Trail.create(trail_name: "Big Fork Ridge Loop", features: "Old Growth Forest", roundtrip: 9.3,  elevation_gain: 1800, difficulty:  9, description:"Big Fork Ridge Loop Trail is a 9 mile moderately trafficked loop trail located near Waynesville, North Carolina that features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is accessible year-round. Horses are also able to use this trail.", image_url: "https://res.cloudinary.com/dhzstgmsp/image/upload/v1646153594/Smoky%20Mountains%20Trails/Big_Fork_Ridge_Loop_bbystk.png" )

